var blogpostData = [
  {
    title:        'Cupcakes',
    author:       'Cupcake Catie',
    sourceTitle:  'Cupcakes 4evr Blog',
    sourceUrl:    'http://www.google.com',
    published:    '2015-11-05',
    content:      '<img src="images/cupcakes.jpg" /><p class="clearfix">Cupcake ipsum dolor sit. Amet cookie cookie ice cream caramels pudding bear claw. Tiramisu topping powder biscuit tiramisu jelly beans muffin chocolate. Topping biscuit tootsie roll carrot cake sweet fruitcake ice cream. Souffle sugar plum souffle candy canes caramels chocolate bar chocolate bear claw. Caramels topping sesame snaps jelly macaroon halvah. Gummi bears jujubes chocolate cake sweet jelly beans. Cake cake tart jelly-o pastry. Donut fruitcake fruitcake.</p><div class="recipe-view"><h3>Cupcakes</h3><p class="recipeheaders">Ingredients</p><ul><li>2 C flour</li><li>1 C sguar</li><li>4 large eggs</li><li>2 t vanilla</li><li>1/2 t salt</li></ul><p class="recipeheaders">Instructions</p><ol><li>Melt the carrot cake sesame snaps croissant.</li><li>Add the cake dragee liquorice I love chocolate caramels lollipop.</li><li>Sift the lollipop apple pie toffee candy canes gummi bears.</li><li>Mix together topping pie cookie.</li><li>Bake for 30 minutes ice cream croissant jelly-o chocolate cake.</li><li>Cool for gingerbread ice cream I love bonbon muffin.</li></ol><p>Liquorice macaroon dessert marzipan. Candy canes cookie chocolate cake sweet roll cupcake ice cream donut. Croissant lollipop powder bear claw lemon drops sweet marzipan macaroon. Lollipop danish gummi bears biscuit. Croissant dessert pie brownie ice cream. Jelly beans cheesecake bear claw sweet roll pie chocolate. Cookie toffee topping cupcake chocolate bar gummi bears powder sweet roll. Sesame snaps souffle halvah halvah tart sesame snaps.</p></div>'
  },
  {
    title:        'Donuts',
    author:       'Donut Donna',
    sourceTitle:  'Donna\'s Blog All About Donuts and Donut Accessories',
    sourceUrl:    'http://www.google.com',
    published:    '2014-12-01',
    content:      '<img src="images/donuts2.jpg" /><p class="clearfix">Cupcake ipsum dolor sit amet macaroon. Tart ice cream chocolate cake croissant fruitcake. Muffin lemon drops apple pie sweet roll croissant chocolate bar. Apple pie candy canes muffin candy canes lollipop cake chocolate cake macaroon. Jelly icing brownie. Liquorice dragee chocolate bonbon sweet lollipop ice cream cookie. Ice cream toffee pudding toffee chocolate cake jelly beans chocolate bar jelly. Cake lollipop gingerbread dragee liquorice chocolate cake sugar plum cotton candy sweet.</p><div class="recipe-view"><h3>Donuts</h3><p class="recipeheaders">Ingredients</p><ul><li>2 C flour</li><li>1 C sguar</li><li>4 large eggs</li><li>2 t vanilla</li><li>1/2 t salt</li></ul><p class="recipeheaders">Instructions</p><ol><li>Melt the carrot cake sesame snaps croissant.</li><li>Add the cake dragee liquorice I love chocolate caramels lollipop.</li><li>Sift the lollipop apple pie toffee candy canes gummi bears.</li><li>Mix together topping pie cookie.</li><li>Bake for 30 minutes ice cream croissant jelly-o chocolate cake.</li><li>Cool for gingerbread ice cream I love bonbon muffin.</li></ol><p>Apple pie oat cake sweet roll marzipan apple pie donut. Sugar plum danish halvah marshmallow lollipop. Pastry apple pie marzipan. Muffin tart candy. Ice cream cake jelly beans toffee cake souffle. Gummies toffee cookie gingerbread caramels marshmallow sugar plum liquorice. Biscuit apple pie candy canes tiramisu muffin carrot cake souffle cake cotton candy.</p></div>'
  },
  {
    title:        'Ice Cream',
    author:       'Ike Creasley',
    sourceTitle:  'The Ice Cream Rules Blog',
    sourceUrl:    'http://www.google.com',
    published:    '2013-06-04',
    content:      '<img src="images/icecream.jpg" /><p class="clearfix">Cupcake ipsum dolor sit amet candy caramels candy lemon drops. Croissant pudding sweet oat cake carrot cake. Gummi bears danish oat cake caramels gummi bears. Bear claw cake donut jelly-o cotton candy chocolate bar tiramisu halvah. Cupcake topping dragee icing pudding bonbon. Sugar plum liquorice cake tootsie roll dessert cake chocolate.</p><div class="recipe-view"><h3>Ice Cream</h3><p class="recipeheaders">Ingredients</p><ul><li>2 C flour</li><li>1 C sguar</li><li>4 large eggs</li><li>2 t vanilla</li><li>1/2 t salt</li></ul><p class="recipeheaders">Instructions</p><ol><li>Melt the carrot cake sesame snaps croissant.</li><li>Add the cake dragee liquorice I love chocolate caramels lollipop.</li><li>Sift the lollipop apple pie toffee candy canes gummi bears.</li><li>Mix together topping pie cookie.</li><li>Bake for 30 minutes ice cream croissant jelly-o chocolate cake.</li><li>Cool for gingerbread ice cream I love bonbon muffin.</li></ol><p>Liquorice souffle jujubes jelly beans pudding tart fruitcake. Cotton candy powder gingerbread cake lemon drops topping marzipan. Jelly-o biscuit sweet roll pie cupcake cookie brownie. Tootsie roll oat cake pie jelly beans tootsie roll cupcake gummies muffin chupa chups. Cotton candy fruitcake carrot cake lemon drops icing caramels cupcake. Tart icing cupcake apple pie souffle gummi bears gingerbread marzipan. Tiramisu gummies souffle cotton candy jelly cookie dragee cake tiramisu. Cupcake bear claw cupcake topping cupcake ice cream dessert bear claw. Powder sesame snaps marshmallow chocolate bar ice cream.</p></div>'
  },
  {
    title:        'Pie',
    author:       'Guy the Pie Guy',
    sourceTitle:  'My Pie Blog',
    sourceUrl:    'http://www.google.com',
    published:    '2016-01-01',
    content:      '<img src="images/pie.jpg" /><p class="clearfix">Cupcake ipsum dolor sit amet croissant. Tiramisu sweet muffin gummies wafer ice cream bear claw. Toffee sweet roll wafer marshmallow icing cotton candy danish halvah lemon drops. Carrot cake liquorice icing cupcake. Biscuit gummies lollipop. Marzipan cookie chupa chups topping muffin chocolate cake ice cream cheesecake dragee. Biscuit ice cream chupa chups lollipop sugar plum lemon drops. Apple pie jelly-o souffle. Chocolate cake pastry biscuit lollipop jujubes.</p><div class="recipe-view"><h3>Pie</h3><p class="recipeheaders">Ingredients</p><ul><li>2 C flour</li><li>1 C sguar</li><li>4 large eggs</li><li>2 t vanilla</li><li>1/2 t salt</li></ul><p class="recipeheaders">Instructions</p><ol><li>Melt the carrot cake sesame snaps croissant.</li><li>Add the cake dragee liquorice I love chocolate caramels lollipop.</li><li>Sift the lollipop apple pie toffee candy canes gummi bears.</li><li>Mix together topping pie cookie.</li><li>Bake for 30 minutes ice cream croissant jelly-o chocolate cake.</li><li>Cool for gingerbread ice cream I love bonbon muffin.</li></ol><p>Marzipan powder candy candy tiramisu dessert cake. Marshmallow bear claw candy canes cake pastry. Sweet cheesecake macaroon brownie gummi bears jelly-o. Topping danish sweet roll marzipan liquorice. Dragee dragee lemon drops icing. Toffee marshmallow chocolate bar.</p></div>'
  },
];
